name: validate
on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:
    branches-ignore:
      - renovate/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: -v --timeout=5m

      - name: Run tests
        run: go test -cover --race ./...
